spring:
  application:
    name: Spring Boot Java Project (Email Service)
  main:
    banner-mode: off
    web-application-type: none # disable web server
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9093

logging:
  level:
    root: warn

# Custom environment variables
custom:
  email: "dniharika16@gmail.com"
