# ------------------------------------------------------------
# 🛑 Note: variables declared in environment will override env_file if same field exists
# .env file must be in same directory as docker-compose.yml
# ------------------------------------------------------------

services:
  main-application:
    container_name: main-application
    image: niharikadutta/main-application:v0.0.1
    ports:
      - "4040:4040"
    volumes: # bind mount
      - ./videos:/app/videos
      - ./config/main-application/application.yml:/app/config/application.yml:ro # host_path : container_path
      - ~/.aws:/root/.aws:ro # mount aws credentials
    command: ["--spring.config.location=file:/app/config/application.yml"]
    env_file:
      - .env
    networks:
      - videohub-network

  processor-service-240p:
    container_name: processor-service-240p
    image: niharikadutta/processor-service:v0.0.1
    # profiles: ["240p"]
    volumes:
      - ./videos:/app/videos
      - ./config/processor-service/application.yml:/app/config/application.yml:ro
      - ~/.aws:/root/.aws:ro
    environment:
      - GROUP_ID=group1
      - RESOLUTION=240p
      - JAVA_OPTS=-DGROUP_ID=group1 -DRESOLUTION=240p -Dspring.devtools.livereload.enabled=false -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -Djdk.util.jar.enableMultiRelease=false -XX:+DisableAttachMechanism
    env_file:
      - .env
    networks:
      - videohub-network

  processor-service-360p:
    container_name: processor-service-360p
    image: niharikadutta/processor-service:v0.0.1
    # profiles: ["360p"]
    volumes:
      - ./videos:/app/videos
      - ./config/processor-service/application.yml:/app/config/application.yml:ro
      - ~/.aws:/root/.aws:ro
    environment:
      - GROUP_ID=group2
      - RESOLUTION=360p
      - JAVA_OPTS=-DGROUP_ID=group2 -DRESOLUTION=360p -Dspring.devtools.livereload.enabled=false -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -Djdk.util.jar.enableMultiRelease=false -XX:+DisableAttachMechanism
      # Kafka connection settings
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
      # - SPRING_KAFKA_CONSUMER_PROPERTIES_SESSION_TIMEOUT_MS=30000
      # - SPRING_KAFKA_CONSUMER_PROPERTIES_REQUEST_TIMEOUT_MS=60000
    env_file:
      - .env
    networks:
      - videohub-network

  processor-service-720p:
    container_name: processor-service-720p
    image: niharikadutta/processor-service:v0.0.1
    # profiles: ["720p"]
    volumes:
      - ./videos:/app/videos
      - ./config/processor-service/application.yml:/app/config/application.yml:ro
      - ~/.aws:/root/.aws:ro
    environment:
      - GROUP_ID=group3
      - RESOLUTION=720p
      - JAVA_OPTS=-DGROUP_ID=group3 -DRESOLUTION=720p -Dspring.devtools.livereload.enabled=false -XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -Djdk.util.jar.enableMultiRelease=false -XX:+DisableAttachMechanism
    env_file:
      - .env
    networks:
      - videohub-network

  email-service:
    container_name: email-service
    image: niharikadutta/email-service:v0.0.1
    environment:
      - JAVA_OPTS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -Djdk.util.jar.enableMultiRelease=false -XX:+DisableAttachMechanism
    volumes:
      - ./config/email-service/application.yml:/app/config/application.yml:ro
    # If email-service has an HTTP port too, publish a different host port
    # ports:
    #   - "4041:4040"

networks:
  videohub-network:
    driver: bridge
    external: true
