services:
  mysql:
    image: mysql:9.0
    container_name: db-mysql-videohub
    restart: always
    environment:
      MYSQL_DATABASE: "videohub"
      MYSQL_USER: "niharika" # NO permission. Need to grant required permissions
      MYSQL_PASSWORD: "pwniharika"
      MYSQL_ROOT_PASSWORD: "pwroot" # username: root
    ports:
      - "3307:3306" # [host_port : container_port] for tcp protocol
    volumes:
      - ./.mysql-data:/var/lib/mysql # config path for mysql image
    networks:
      - videohub-network

networks:
  videohub-network:
    name: videohub-network
    driver: bridge
    external: true # the network must exist already
# https://hub.docker.com/_/mysql
# https://docs.docker.com/reference/compose-file/networks/

# not mentioning the port in the command as itwill use the default port 3306
# mysql -u root
# mysql -u root -h localhost -P 3306

# mysql -u niharika -p -h localhost -P 3307 videohub
# mysql -u root -P 3307
# mysql -u root -p -h 127.0.0.1 -P 3307

# SELECT User, Host FROM mysql.user;
# docker exec -it db-mysql-videohub mysql -u root -p

