#server:
#  port: ${PORT}

spring:
  application:
    name: Spring Boot Java Project (Consumer)
  main:
    banner-mode: off
  servlet:
    multipart:
      max-file-size:    50MB
      max-request-size: 50MB
  datasource:
    url:      "jdbc:mysql://localhost:3307/videohub" # "3.140.188.132:3306" JDBC URL of the database
    username: "root" # username and password for Database
    password: "pwroot"
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9093 # 3.140.188.132:9093
  devtools:
    livereload:
      enabled: false

# Reduce logging level
logging:
  level:
    root: warn # log only warning and error

# Custom environment variables
custom:
  target-resolution-count: 3
  path:
    process-success-email-template: "/Users/niharika/Workspace/Personal/IntellijProjects/project-videohub/java-project-part2/image_process_success_email.md"
    image-collection-dir:           "/Users/niharika/Workspace/Personal/IntellijProjects/project-videohub/photoGallery"
  ffmpeg:
    path:  "/opt/homebrew/bin/ffmpeg"
    probe: "/opt/homebrew/bin/ffprobe"




# ----- reference for deployment -----
#    process-success-email-template: "/home/ubuntu/javaproject/part2/image_process_success_email.md"
#    image-collection-dir: "/home/ubuntu/javaproject/photoGallery"

#command to run jar
# java -jar -DHEIGHT=128 -DWIDTH=128 -DGROUP_ID=group1 ./target/pixprocessor-service-0.0.1-SNAPSHOT.jar
