spring:
  application:
    name: Spring Boot Java Project (Consumer)
  main:
    banner-mode: off
    web-application-type: none # disable web server
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  datasource:
    url: "jdbc:mysql://mysql:3306/videohub"
    username: "root"
    password: "pwroot"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  devtools:
    livereload:
      enabled: false
  kafka:
    bootstrap-servers: 100.88.115.16:9093

logging:
  level:
    root: warn

# Custom environment variables
custom:
  target-resolution-count: 6
  path:
    project-root-dir: ${CUSTOM_PATH_PROJECT_ROOT_DIR:/app}
  ffmpeg:
    path: ${FFMPEG_PATH:/opt/homebrew/bin/ffmpeg}
    probe: ${FFPROBE_PATH:/opt/homebrew/bin/ffprobe}
aws:
  credentials:
    profile: ${AWS_PROFILE}
    region: ${AWS_REGION}
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
