spring:
  application:
    name: Spring Boot Java Project (Consumer)
  main:
    banner-mode: off
    web-application-type: none
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: "jdbc:mysql://db:3306/videohub"
    username: "root"
    password: "pwroot"
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: localhost:9093
  devtools:
    livereload:
      enabled: false

logging:
  level:
    root: warn

custom:
  target-resolution-count: 6
  path:
    project-root-dir: "/Users/niharika/Workspace/Personal/IntellijProjects/video-hub"
    process-success-email-template: "/Users/niharika/Workspace/Personal/IntellijProjects/video-hub/main-application/video_process_success_email.md"
    image-collection-dir: "/Users/niharika/Workspace/Personal/IntellijProjects/video-hub/photoGallery"
  ffmpeg:
    path: "/opt/homebrew/bin/ffmpeg"
    probe: "/opt/homebrew/bin/ffprobe"

aws:
  credentials:
    profile: "shaktiman"
    region: "us-east-1"
  s3:
    bucket-name: "demobucket-890291224"
# ----- reference for deployment -----
#    process-success-email-template: "/home/ubuntu/javaproject/part2/image_process_success_email.md"
#    image-collection-dir: "/home/ubuntu/javaproject/photoGallery"

#command to run jar
# java -jar -DHEIGHT=128 -DWIDTH=128 -DGROUP_ID=group1 ./target/pixprocessor-service-0.0.1-SNAPSHOT.jar
